syntax = "proto3";

package focus.v1;

service FocusService {
  rpc Focus(FocusRequest) returns (FocusResponse);
  rpc Claim(ClaimRequest) returns (ClaimResponse);
  rpc Reply(ReplyRequest) returns (ReplyResponse);
}

message FocusRequest {
  string env_id = 1;
  string path = 2;
}

message FocusResponse {
  optional string error = 1;
}

message ClaimRequest {
  string env_id = 1;
}

message ClaimResponse {
  uint32 reply_id = 1;
  string path = 2;
}

message ReplyRequest {
  uint32 reply_id = 1;
  optional string error = 2;
}

message ReplyResponse {}
