syntax = "proto3";

package submit.v1;

service SubmitService {
  rpc Submit(SubmitRequest) returns (SubmitResponse);
  rpc Subscribe(SubscribeRequest) returns (stream SubscribeResponse);
  rpc Callback(CallbackRequest) returns (CallbackResponse);
}

message SubmitRequest {
  string problem_id = 1;
  string file_name = 2;
  bytes content = 3;
}

message SubmitResponse {}

message SubscribeRequest {
  string problem_id = 1;
}

message SubscribeResponse {
  string callback_id = 1;
  string file_name = 2;
  bytes content = 3;
}

message CallbackRequest {
  string callback_id = 1;
  string error = 2;
}

message CallbackResponse {}